<template>
  <div>
	<img :src="assetPath('Universes', 'TitreMnimeyo')" alt="Planet name" v-if="isUniverse">
		<div v-bar>
			<div>
				<p>
					Tourism is a phenomenon that implies the moving of persons to a foreign location. If at the beginning, travelling was reserved for the most privileged, it became over time democratized. The 21st century has brought us into mass tourism, in particular with increasingly attractive offers and more destinations. On the opposite of its economic benefits, other effects have emerged that countries consider negative. For instance, touristic destinations are experiencing an increase in pollution due to increased waste or means of transportation such as boats affect biodiversity. We also talk of overbuilding when tourist-related constructions impinge on green areas.
				</p>
				<h2>{{"Making the tourists accountable".toUpperCase()}}</h2>
				<img :src="assetPath('Universes', 'barre')" alt="Line">

				<p>
					A news article of Inrocks explains that in Europe, several demonstrations took place against the inconvenience implied by having too many tourists. The term <strong>tourismophobia</strong> is used to define these anti-tourist protests, a word which made its way in a Spanish article of <em>20minutos</em>. Indeed, an activist group in Spain is campaigning not against tourism nor tourists but rather against the massification of it. In Palma de Mallorca, the walls have been painted with some graffiti <em>“Stop tourism”, “Refugees welcome, Tourists go home”</em>. Another demonstration was held in Barcelona where tourism is certainly an economic pillar for the city, but it also raises housing prices, locals are feeling scammed by hotels and other tourist traps. For example, rents have increased between 9 and 18% in Barcelona. We are talking about "Folklorization", tourists think they are experiencing the traditional culture of the country but in truth, they are given a staged entertainment rather than the reality experienced by the locals. This is also the case in Thailand, where too many tourists cause a degradation of the local environment. In 2016, the government banned the use of fast boats around Phuket to avoid the destruction of coral reefs. In fact, a news article from Thailand asserts that 77% of coral reefs have been damaged.
					<br/>
					In Europe, we try to change things with sustainable tourism : they are trying to make tourists aware of their harmful behavior during their travels, make them responsible. For example, the tourist site of Venice encourages "detourism", that is to say discovering the city like the Venetians and going beyond the very tourist sites. The British newspaper <em>The Guardian</em> explains that countries should also stop seeing their own land as a source of operations but rather as a sacred land that needs to be protected.
				</p>
				<p>
					Yet, countries are still trying to develop their tourism sector. An <em>RFI</em> article presents tourism as an engine of growth for West and North African countries. <em>L'Echos</em> explains that tourists come from 65% of sub-Saharan Africa and 40% of the whole continent. Senegal has lowered hotel and airport taxes and removed the fee-paying visa in 2015. Senegal's goal is to attract 3 million travelers by 2023. However, it still take 9 visas to visit the African continent from North to South, by car. Not to mention that there is still a great lack of infrastructure that makes the hosting potential quite difficult. At the same time, Morocco was the leading tourist destination in Africa in 2016. French people represent 30% of travelers. In an Afrik.com article, it is explained that even if southern Africa manages to attract tourists, the Sahelian zone is affected by a climate of insecurity. This region is shaken by insecurity generated by armed gangs and terrorism but also political instability. It suffers a crisis of governance, meaning that the State which should serve the people is non existent. The population is simply abandoned. In 2016, Northern Mali suffered more than 385 attacks, an increase of 92% compared to 2015.
				</p>
				<h2>{{"Places of crimes against humanity open to visitors".toUpperCase()}}</h2>
				<img :src="assetPath('Universes', 'barre')" alt="Line">
				<p>
					In the United States, some old plantations are open to visitors. For example, Whitney plantation is dedicated to the memory of the slaves. It’s a first because other plantations put more emphasis on the beauty of the places and buildings. In an article by Slate.fr, a Yale historian, Jonathan Holloway explains:
				</p>
				<p>
					<em>"Traditionally, planting tours were opportunities to celebrate the refined lives of the owners and the culture of the South. And then people started to ask, but who built all that? "</em>
				</p>
				<p>
					He adds that, at Whitney, the historical axis is completely different because it is centered on slaves:
				</p>
				<p>
					<em>"(...) we start with the memorials with the names of slaves, then the huts and we end up in the big house. It completely reverses the meaning of the story. We start in a black space to arrive in a white space. It's a very strong reorientation. "</em>
				</p>
				<p>
					The context of the country explains this change, including the Charleston massacre of June 17 which claimed 9 African-American victims. Ibrahima Seck, Research Director of Whitney Plantation, says:
				</p>
				<p>
					<em>"The supremacist ideas of the Charleston killer have been peddled since the time of slavery. We must educate people, both the descendants of the masters and the descendants of the slaves."</em>
				</p>
				<p>
					Here it is more about memory, education and lesson through History. In Brazil, in the region of Rio, Paraiba Valley, another former slave property promises to immerse you in the colonial era. However, this plantation has been sharply criticized because visitors are greeted by black people dressed as slaves. An article from <em>The Intercept</em> has dug up the controversy: the author criticizes the fact that tourists cannot have a critical perspective on the violence and horror of slavery when they are invited to listen to an intimate concert, while being served by people dressed as slaves.
				</p>
				<p>
					Another example is the former Auschwitz-Birkenau concentration camp, located in Poland, which has welcome millions of visitors from all over the world since 1955. The camp almost closed due to the high costs needed to maintain the site. Donald Tusk, head of the Polish government, asked for donations in 2009:
				</p>
				<p>
					<em>"To save Auschwitz-Birkenau is to save the memory of millions of people who suffered and were brutally murdered. It is the responsibility and the duty of the whole Europe"</em>
				</p>
				<p>
					In answer to this request, 100,000,000 euros were raised by more than 28 countries. Since then, attendance has increased and is becoming more and more harmful to buildings. Some visitors do not respect the place and are seen engraving their names on the walls. Beyond that, the locals are asking to not dwell on the past and move on as assistant Director-General for culture at UNESCO, Francesco Bandarin mentions:
				</p>
				<p>
					<em>"The management issue concerning the surroundings remains intact: the inhabitants would like to have a normal life, they don’t understand why everything should be rigid, the young people want a night club. The philosophical debate on the triviality of evil is relentless. We have to study things closely, those of the living, not just those of the dead."</em>
				</p>
				<p>
					Robert Jan Van Pelt, a Dutch historian and author, also referred to Auschwitz as <em>"a sanitized theme park for tourists"</em> in a 2009 BBC article. He added that the camp should disappear along with the last survivor. He considers that  a ground-zero would be more striking than showing its reconstruction, as faithful but contrived.
				</p>
			</div>
			<div class="dragger-back"></div>
		</div>
		<button @click="quittingPlanet()" v-if="isUniverse">NEXT UNIVERSE <span>►</span></button>
	</div>
</template>

<script>
export default {
	name: "planet2",
	data() {
		return {};
	},
	computed: {},
	methods: {
		quittingPlanet() {
			this.$emit("quittingPlanet");
		}
	},
	props: ["isUniverse"]
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style>

</style>
