const state = {
	countriesList: {
		EastAsia: ["China", "North Korea", "South Korea", "Japan"],
		Europe: [
			"Albania",
			"Andorra",
			"Armenia",
			"Austria",
			"Belgium",
			"Belarus",
			"Bosnia and Herzegovina",
			"Bulgaria",
			"Cyprus",
			"Czech Republic",
			"Croatia",
			"Denmark",
			"Estonia",
			"Finland",
			"France",
			"Georgia",
			"Germany",
			"Greece",
			"Hungary",
			"Iceland",
			"Ireland",
			"Italy",
			"Latvia",
			"Liechtenstein",
			"Lithuania",
			"Luxembourg",
			"Macedonia",
			"Malta",
			"Moldova",
			"Monaco",
			"Montenegro",
			"Netherlands",
			"Norway",
			"Poland",
			"Portugal",
			"Romania",
			"Russia",
			"Serbia",
			"Slovakia",
			"Slovenia",
			"Spain",
			"Sweden",
			"Switzerland",
			"Ukraine",
			"United Kindgom",
			"Vatican",
			"Guadeloupe",
			"Martinique",
			"French Guiana",
			"Reunion",
			"Mayotte",
			"Saint Pierre and Miquelon",
			"Saint Barthélemy",
			"Saint Martin",
			"Sint Maarten",
			"Wallis and Futuna Islands",
			"French Polynesia",
			"New Caledonia"
		],
		NorthAfrica: ["Algeria", "Egypt", "Libya", "Morocco", "Tunisia"],
		NorthAmerica: [
			"Antigua and Barbuda",
			"Bahamas",
			"Barbados",
			"Belize",
			"Canada",
			"Costa Rica",
			"Cuba",
			"Dominica",
			"Dominican Republic",
			"El Salvador",
			"Grenada",
			"Guatemala",
			"Haiti",
			"Honduras",
			"Jamaica",
			"Mexico",
			"Nicaragua",
			"Panama",
			"Saint Kitts and Nevis",
			"Saint Lucia",
			"Saint Vincent and the Grenadines",
			"Trinidad and Tobago",
			"United States"
		],
		MiddleEast: [
			"Afghanistan",
			"Azerbaijan",
			"Bahrain",
			"Iran",
			"Iraq",
			"Israel",
			"Jordan",
			"Kazakhstan",
			"Kuwait",
			"Lebanon",
			"Oman",
			"Palestinian Territories",
			"Qatar",
			"Saudi Arabia",
			"Syria",
			"Turkey",
			"United Arab Emirates",
			"Yemen"
		],
		NorthAsia: [
			"Kazakhstan",
			"Kyrgyzstan",
			"Mongolia",
			"Nepal",
			"Tajikistan",
			"Turkmenistan",
			"Uzbekistan"
		],
		Oceania: [
			"Australia",
			"Cook Islands",
			"Fiji",
			"Kiribati",
			"Marshall Islands",
			"Micronesia",
			"Niue",
			"New Zealand",
			"Palau",
			"Papua New Guinea",
			"Samoa",
			"Solomon Islands",
			"Tonga",
			"Tuvalu",
			"Vanuatu"
		],
		SouthAmerica: [
			"Argentina",
			"Bolivia",
			"Brazil",
			"Chile",
			"Colombia",
			"Ecuador",
			"Guyana",
			"Paraguay",
			"Peru",
			"Suriname",
			"Uruguay",
			"Venezuela"
		],
		SouthAsia: [
			"Bangladesh",
			"Bhutan",
			"Burma",
			"Brunei",
			"Cambodia",
			"India",
			"Indonesia",
			"Laos",
			"Malaysia",
			"Maldives",
			"Pakistan",
			"Philippines",
			"Singapore",
			"Sri Lanka",
			"Thailand",
			"Timor-Leste",
			"Vietnam"
		],
		SubSaharanAfrica: [
			"Angola",
			"Benin",
			"Botswana",
			"Burkina Faso",
			"Burundi",
			"Cameroon",
			"Cabo Verde",
			"Central African Republic",
			"Chad",
			"Comoros",
			"Cote d'Ivoire",
			"Democratic Republic of the Congo",
			"Djibouti",
			"Equatorial Guinea",
			"Eritrea",
			"Ethiopia",
			"Gabon",
			"Gambia",
			"Ghana",
			"Guinea",
			"Guinea-Bissau",
			"Kenya",
			"Lesotho",
			"Liberia",
			"Madagascar",
			"Malawi",
			"Mali",
			"Mauritania",
			"Mauritius",
			"Mozambique",
			"Namibia",
			"Niger",
			"Nigeria",
			"Republic of the Congo",
			"Rwanda",
			"Sao Tome and Principe",
			"Senegal",
			"Seychelles",
			"Sierra Leone",
			"Somalia",
			"South Sudan",
			"Sudan",
			"Swaziland",
			"Tanzania",
			"Togo",
			"Uganda",
			"Zambia",
			"Zimbabwe"
		]
	}
};

export default {
	state
};
